### ISSUE TITLE
Latest release of Nop.Plugin.Api.Tests does not compile

### ISSUE THREAD

**Issue by alaingmail** [SevenSpikes/nopCommerce-Api-SampleApplication#1]
Hi,

The latest release of this web api branch does not compile for Nop.Plugin.Api.Tests. I downloaded it yesterday. I did not clone it. That should not make a difference.

Here are the errors I'm seeing:

- The type or namespace name 'ISerializableObject' could not be found (are you missing a using directive or an assembly reference?)	Nop.Plugin.Api.Tests	D:\_depot\Test\nopCommerce-Web-Api-3.70\src\Tests\Nop.Plugin.Api.Tests\SerializersTests\DummyObjects\SerializableDummyObjectWithSimpleTypes.cs. This was corrected by adding "using Nop.Plugin.Api.DTOs;" to SerializableDummyObjectWithComplexTypes.cs.

- The same error occurs for SerializableDummyObjectWithSimpleTypes.cs with the same fix.

- The type or namespace name 'CreateMap' does not exist in the namespace 'Nop.Plugin.Api.Maps' (are you missing an assembly reference?)	Nop.Plugin.Api.Tests	D:\_depot\Test\nopCommerce-Web-Api-3.70\src\Tests\Nop.Plugin.Api.Tests\ControllersTests\ShoppingCartItems\ShoppingCartItemsControllerTests_GetShoppingCartItemsByCustomerId.cs. This occurs for "Maps.CreateMap<Category, CategoryDto>();". I'm assuming this is an AutoMapper map definition, but I'm not faimiliar with this format. Changing to **AutoMapper.Mapper.CreateMap<Category, CategoryDto>();** works.

Cheers,
Alain

**Comment by alaingmail** [comment]
Hi,

I just realised I've added this issue to the wrong repo. Although the other repo (https://github.com/SevenSpikes/nopCommerce/tree/Web-Api-3.70) does not have the ability to add issues. At least not when I'm looged in.

**Comment by poyker** [comment]
Hi Alain,

Thank you for reporting this!

We enabled the Issues on the other repo so you should be able to create issues.
I will close this one.
