### ISSUE TITLE
I'm not sure what this is in reference to: objectPropertyNameValuePairs

### ISSUE THREAD

**Issue by techgeeksquared** [SevenSpikes/nopCommerce-Api-SampleApplication#7]
I am trying to create new categories however, I'm not sure objectPropertyNameValuePairs is in reference to.

Could someone please provide some guidance? 

This looks to have no content.
https://github.com/SevenSpikes/api-plugin-for-nopcommerce/blob/nopcommerce-3.80/Categories.md

Thank you.

**Comment by poyker** [comment]
@techgeeksquared 

You are right. There is still no documentation for the categories endpoint.
You can use Swagger only for GET and DELETE commands but you can't use it for POST and PUT, so don't use it as a reference. Actually the format that it shows for POST is incorrect. It says that you should use "categories" while actually you need to use "category" as the root json property (as you have already [noted](https://github.com/SevenSpikes/api-plugin-for-nopcommerce/issues/51)).

We will update the documentation as soon as we have some free time to do so.

**Comment by BabuBahir** [comment]
I have done a detailed study of nopcommerce and the rest api plugin...

I found that the post and put for all elements have been written in the code ...but however the swagger documentation only shows an  "**_

> objectPropertyNameValuePairs

_** "

when we wish to put/post .......
